.PHONY: all run tui test build clean help

# 默认直接构建并启动 TUI
all: run

run:
	@./run.sh tui

tui:
	@./run.sh tui

test:
	@./run.sh test

build:
	@./run.sh build

clean:
	@./run.sh clean

help:
	@./run.sh help
